name: 'TRX to VS Playlist Converter (JS with pre)'
description: 'JavaScript wrapper that installs trx-to-vsplaylist in a pre step and runs the conversion.'

inputs:
  trx-file-path:
    description: 'Path or glob pattern to the TRX file(s) to convert.'
    required: true
  output-directory:
    description: 'Directory to write the output playlist file(s) to.'
    required: false
  test-outcomes:
    description: 'Test outcomes to include in the playlist (comma-separated).'
    required: false
    default: 'Failed'
  skip-empty:
    description: 'Skip writing out empty playlist files. If true, empty playlists will not be created.'
    required: false
    default: 'true'
  separate:
    description: 'When multiple TRX files are found, create separate playlist files for each instead of merging into one.'
    required: false
    default: 'false'

runs:
  using: 'node20'
  pre: 'dist/pre.js'
  main: 'dist/main.js'
