version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly" 
  - package-ecosystem: "npm"
    directory: "/.github/actions/setup-trx-tool"
    schedule:
      interval: "weekly"
