---
name: 'TRX to VS Playlist Converter'
description: >
  Convert TRX test result files to Visual Studio Test playlist files
branding:
  icon: 'play'
  color: 'blue'

inputs:
  trx-file-path:
    description: 'Path to the TRX file to convert'
    required: true
  output-directory:
    description: >
      Directory to write the output playlist file(s) to (optional). If not specified, the
      playlist will be saved in the same directory as the TRX file with the
      same name but .playlist extension.
    required: false
  test-outcomes:
    description: >
      Test outcomes to include in the playlist (comma-separated). Accepts:
      Passed, Failed, NotExecuted, Inconclusive, Timeout, Pending. Default: Failed
    required: false
    default: 'Failed'
  artifact-name:
    description: >
      Name for the uploaded artifact. If not specified, will use the playlist
      file name (without extension).
    required: false
  skip-empty:
    description: >
      Skip writing out empty playlist files. If true, empty playlists will not be created. Default: true
    required: false
    default: 'true'
  combine-playlists:
    description: >
      Combine multiple playlists into a single playlist file with de-duplication. 
      When enabled, all individual playlists are merged into one 'combined.playlist' file. Default: false
    required: false
    default: 'false'

outputs:
  playlist-path:
    description: 'Path to the generated playlist file'
    value: ${{ steps.convert.outputs.playlist-path }}

runs:
  using: 'composite'
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'

    - name: Install trx-to-vsplaylist tool
      shell: bash
      run: |
        echo "Installing trx-to-vsplaylist tool..."
        dotnet tool install --global trx-to-vsplaylist --version 1.1.0
        echo "✅ trx-to-vsplaylist tool installed successfully"

    - name: Convert TRX to Playlist
      id: convert
      shell: bash
      run: |
        # Parse inputs
        TRX_FILE="${{ inputs.trx-file-path }}"
        OUTPUT_DIRECTORY="${{ inputs.output-directory }}"
        OUTCOMES="${{ inputs.test-outcomes }}"
        SKIP_EMPTY="${{ inputs.skip-empty }}"
        COMBINE_PLAYLISTS="${{ inputs.combine-playlists }}"

        # Expand glob patterns to all matching TRX files
        TRX_FILES=($(ls $TRX_FILE 2>/dev/null || echo "$TRX_FILE"))
        if [ ${#TRX_FILES[@]} -eq 0 ]; then
          echo "Error: No TRX file found matching pattern: $TRX_FILE"
          exit 1
        fi

        # Set artifact directory
        if [ -n "$OUTPUT_DIRECTORY" ]; then
          ARTIFACT_DIR="$OUTPUT_DIRECTORY"
        else
          ARTIFACT_DIR="$(dirname "${TRX_FILES[0]}")"
        fi
        mkdir -p "$ARTIFACT_DIR"

        PLAYLIST_PATHS=()
        ARTIFACT_BASENAMES=()
        PROCESSED_TRX_COUNT=0

        for ACTUAL_TRX_FILE in "${TRX_FILES[@]}"; do
          if [ ! -f "$ACTUAL_TRX_FILE" ]; then
            echo "Warning: $ACTUAL_TRX_FILE is not a file, skipping."
            continue
          fi
          PROCESSED_TRX_COUNT=$((PROCESSED_TRX_COUNT+1))
          echo "Using TRX file: $ACTUAL_TRX_FILE"

          TRX_BASENAME=$(basename "$ACTUAL_TRX_FILE" .trx)
          FINAL_OUTPUT="$ARTIFACT_DIR/$TRX_BASENAME.playlist"

          # Build command arguments array
          ARGS=(convert "$ACTUAL_TRX_FILE")
          ARGS+=(--output "$FINAL_OUTPUT")

          if [ "$SKIP_EMPTY" != "false" ]; then
            ARGS+=(--skip-empty)
          fi

          if [ -n "$OUTCOMES" ]; then
            IFS=',' read -ra OUTCOME_ARRAY <<< "$OUTCOMES"
            for outcome in "${OUTCOME_ARRAY[@]}"; do
              outcome=$(echo "$outcome" | xargs)
              ARGS+=(--outcome "$outcome")
            done
          fi

          echo "Running: trx-to-vsplaylist ${ARGS[@]}"
          trx-to-vsplaylist "${ARGS[@]}"

          if [ ! -f "$FINAL_OUTPUT" ]; then
            if [ "$SKIP_EMPTY" = "false" ]; then
              echo "Error: Playlist file was not created at: $FINAL_OUTPUT"
              exit 1
            else
              echo "Info: Playlist file was not created at: $FINAL_OUTPUT (likely due to --skip-empty and no matching tests)"
              continue
            fi
          fi

          echo "Successfully created playlist file: $FINAL_OUTPUT"
          PLAYLIST_PATHS+=("$FINAL_OUTPUT")
          ARTIFACT_BASENAMES+=("$(basename "$FINAL_OUTPUT" .playlist)")
        done

        if [ "$PROCESSED_TRX_COUNT" -eq 0 ]; then
          echo "Error: No valid TRX files were found to process."
          exit 1
        fi

        # Combine playlists if requested
        if [ "$COMBINE_PLAYLISTS" = "true" ] && [ ${#PLAYLIST_PATHS[@]} -gt 0 ]; then
          echo "Combining ${#PLAYLIST_PATHS[@]} playlists into a single combined playlist..."
          COMBINED_PLAYLIST="$ARTIFACT_DIR/combined.playlist"
          
          # Start with playlist header
          echo '<?xml version="1.0" encoding="utf-8"?>' > "$COMBINED_PLAYLIST"
          echo '<Playlist Version="1.0">' >> "$COMBINED_PLAYLIST"
          
          # Create a temporary file to collect all unique test names
          TEMP_TESTS="/tmp/unique_tests.txt"
          > "$TEMP_TESTS"
          
          # Extract test names from all playlists and collect unique ones
          for playlist in "${PLAYLIST_PATHS[@]}"; do
            if [ -f "$playlist" ]; then
              # Extract test names from <Add Test="..." /> lines, handling potential BOM and different formats
              grep -o 'Test="[^"]*"' "$playlist" | sed 's/Test="//;s/"//' >> "$TEMP_TESTS"
            fi
          done
          
          # Sort and de-duplicate test names
          sort -u "$TEMP_TESTS" > "$TEMP_TESTS.sorted"
          
          # Add each unique test to the combined playlist
          while IFS= read -r test_name; do
            if [ -n "$test_name" ]; then
              echo "  <Add Test=\"$test_name\" />" >> "$COMBINED_PLAYLIST"
            fi
          done < "$TEMP_TESTS.sorted"
          
          # Close playlist
          echo '</Playlist>' >> "$COMBINED_PLAYLIST"
          
          # Clean up temp files
          rm -f "$TEMP_TESTS" "$TEMP_TESTS.sorted"
          
          # Count tests in combined playlist
          TEST_COUNT=$(grep -c '<Add Test=' "$COMBINED_PLAYLIST" || echo "0")
          echo "Successfully created combined playlist with $TEST_COUNT unique tests: $COMBINED_PLAYLIST"
          
          # Update outputs for combined playlist
          PLAYLIST_PATHS=("$COMBINED_PLAYLIST")
          ARTIFACT_BASENAMES=("combined")
        fi

        # Output all playlist paths as a colon-separated list
        echo "playlist-paths=${PLAYLIST_PATHS[*]}" | tr ' ' ':' >> $GITHUB_OUTPUT
        echo "artifact-basenames=${ARTIFACT_BASENAMES[*]}" | tr ' ' ':' >> $GITHUB_OUTPUT
        echo "artifact-dir=$ARTIFACT_DIR" >> $GITHUB_OUTPUT

    - name: Upload Playlist Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name || 'playlists' }}
        path: ${{ steps.convert.outputs.artifact-dir }}/*.playlist
        if-no-files-found: 'warn'
